### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gn02168800** [Palatis/Fanuc.RobotInterface#1]
您好，

請問您是購買使用FANUC的開發用API嗎?
也想請問FANUC有安裝Ethernet/IP的話，
是否可以用socket通訊讀寫?

再麻煩您，謝謝

**Comment by Palatis** [comment]
如果找 FANUC 的話，官方是有提供 FANUC Robot Interface（FRRJIF.dll），產品號是 A08B-9410-J575，屬於 FANUC PCDK 的一部分。
原則上每台「開發機」需要一份授權，使用則是不用的。
在 v3.0.0 以前有 USB 鑰匙保護，之後的版本就不再需要。

在手臂控制器上需要
1. `R650 FRA Params + R535 HMI Device (SNPX)`，或是
2. `R651 FRL Params`

EtherNet/IP 是完全不一樣也不相關的東西。
